In [10]:
import numpy as np

##first problem

In [17]:
np1=np.identity(3)
print(np1*9)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


##second problem

In [40]:
np2=np.arange(33)
np2=np2[2:33:2]
np2=np2.reshape(4,4)
standerd_deviation=np.std(np2)
mean=np.mean(np2)
filtered=(np2>mean-0.5*standerd_deviation)&(np2<mean+0.5*standerd_deviation)
print(np2[filtered])


[14 16 18 20]


##Third problem

In [43]:
np3=np.zeros((9,9),dtype='int32')
print(np3)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


##fouth problem

In [56]:
while True:
    try:
        n=int(input("Enter an interger number"))
        break
    except ValueError:
        print("please enter valid input")
    
first_array=np.arange(1,n+1)
np4 = np.tile(first_array, (n, 1))
print(np4)


Enter an interger number 2


[[1 2]
 [1 2]]


##fifth problem(the submitted code doesnot use numpy cause it gives runtime error on codeforces)

In [ ]:
n = int(input())
cards = list(map(int, input().split()))

left = 0
right = n - 1

sereja_score = 0
dima_score = 0

while left <= right:
    if cards[left] > cards[right]:
        sereja_score += cards[left]
        left += 1
    else:
        sereja_score += cards[right]
        right -= 1

    if left <= right:
        if cards[left] > cards[right]:
            dima_score += cards[left]
            left += 1
        else:
            dima_score += cards[right]
            right -= 1

print(sereja_score, dima_score)

             

##fifth problem using numpy(not accepted in  numpy)

In [ ]:
import numpy as np

try:
    n = int(input())
    cards = np.array(list(map(int, input().split())))

    sorted_cards = np.sort(cards)
    sereja_cards = sorted_cards[::-2]

    sereja_sum = np.sum(sereja_cards)
    dima_sum = np.sum(cards) - sereja_sum

    print(sereja_sum, dima_sum)

except Exception as e:
    print("Error:", e)


##The sixth problem

In [59]:
# Read input
n, m = map(int, input().split())
 
# Read photo pixels
photo = [input().split() for _ in range(n)]
 
# Check if the photo is colored
is_colored = False
for row in photo:
    if 'C' in row or 'M' in row or 'Y' in row:
        is_colored = True
        break
 
# Output result
if is_colored:
    print("#Color")
else:
    print("#Black&White")

 2 2
 C M
 Y Y


#Color
